### ISSUE TITLE
addFineFlux for single block of flux data

### ISSUE THREAD

**Issue by pajkosmi** [ECP-Astro/FLASH5#595]
In the context of per level flux correction for AMR, the ```Grid_addFineToFluxRegister``` routine presently works for updating an entire level of refinement per iteration.

The spark hydrodynamic solver, by contrast, is a two stage solver that operates on a per block basis.  This behavior implies that spark may require more than one block iteration to completely update a given level of refinement.  Thus, there is motivation to create a modified ```Grid_addFineToFluxRegister``` routine that can modify the flux registers for a single block of data, rather than the entire level. Likewise, being able to scale the fluxes by a constant before placing them in the register would be advantageous.

One of spark's strengths is its ability to save on communication cost by leveraging this 2 stage Runge-Kutta flux treatment.  This treatment requires that the interior cells and a halo of NSTENCIL (defined in Flash.h) number of cells be updated during stage 1.  Only the interior cells are updated during stage 2.  As outlined in ```AMR/Amrex/Grid_tile.F90```, the current ```tileDesc%getDataPtr(...,FLUXX)``` call accesses multifabs that are hardwired at creation to only account for block interiors.  In order to use the given ```tileDesc%getDataPtr(...,FLUXX)``` format, they would need to contain at least 2xNSTENCIL number of additional cells (NSTENCIL number for each direction).  For reference, the fluxes are currently stored in ```Hydro_data.F90``` in ```hy_fl[xyz]``` terms that have memory allocated for every guard cell.

As a point of clarity, the guard cell face fluxes are needed for this 2 stage update.  For flux correction---which occurs after the update---only the faces of the interior zone need to be stored in the register.

**Comment by jared321** [comment]
Please refer to Issue #190 for more information about this request.  Closed.
