### ISSUE TITLE
gr_makeMaskConsistent setting needEos unnecessarily

### ISSUE THREAD

**Issue by jaharris87** [ECP-Astro/FLASH5#634]
Relevant LOC: https://github.com/ECP-Astro/FLASH5/blame/master/source/Grid/GridMain/AMR/paramesh/paramesh4/gr_makeMaskConsistent.F90#L378

```Fortran
  !! If any energy variable is set to true then eos call is needed DEV:: why ?
  needEos= gcell_on_cc(ENER_VAR).or.gcell_on_cc(EINT_VAR).or.needEos 
```

I do not believe it is necessary to always set `needEos` to `.true.`. This is particularly salient radiation transport, where we have something like:
```
loop over refinement levels
  calculate dt_transport ! function of dx_level
  do while t < dt_level
    Grid_fillGuardCells(...) ! need ghost cells for variables below
    iterate over tiles
      load inputs from UNK (DENS_VAR,VEL{X,Y,Z}_VAR,ENER_VAR,YE_MSCALAR)
      evolve transport(dt_level)
      save outputs to UNK (VEL{X,Y,Z}_VAR,ENER_VAR,EINT_VAR,YE_MSCALAR)
    end iterate
  end do while
end level loop
call Eos_everywhere(MODE_DENS_EI)
```

**Comment by jaharris87** [comment]
Is this one of the intended purposes of `Grid_guardCellMaskHook`---to override decisions like this?
It looks like this is basically a stub at the moment, even for Paramesh.

**Comment by kweide** [comment]
The intended purpose is to allow physics units to add knowledge about __additional__ variable dependencies. It was not intended to remove from the dependencies that are already hardwired in gr_makeMaskConsistent. It was also not intended to modify the `needEos` flag (which is, after all, `INTENT(IN)` to it).

**Comment by kweide** [comment]
In FLASH4 there were implementations of Burn and Simulation that actually modify the mask.

**Comment by kweide** [comment]
`Grid_fillGuardCells` should never call `Eos` unless the former's optional argument `doEos` is set and true.

**Comment by jaharris87** [comment]
> `Grid_fillGuardCells` should never call `Eos` unless the former's optional argument `doEos` is set and true.

This was the missing piece in my understanding.
I added a hook for `RadTrans_guardCellMaskHook` in my feature development branch to set additional elements of the mask, but this is a separate issue.

I'm closing this issue now.
